// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibhpbtamnpqrdfveezwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImliaHBidGFtbnBxcmRmdmVlendmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDgwNjUsImV4cCI6MjA2ODg4NDA2NX0.GdQTjRkwijqbnK0pFx2UZ3P3DczMXNi0T_Jhae0SSu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});