// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwubyskxnflyvkqmvytf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3dWJ5c2t4bmZseXZrcW12eXRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDIwMzgsImV4cCI6MjA2ODg3ODAzOH0.Y10EOZDCyDn2BK9lUYgos9bKNxzboQaDnSRjVrQZn2k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});